ABET_files = {...
    'RRD399 12132023 ABET.csv';...
    'RRD400 12182023 ABET.csv';...
    'RRD401 12072023 ABET.csv';...
    'RRD403 12072023 ABET.csv';...
    'RRD404 12072023 ABET.csv';...
    'RRD405 12162023 ABET.csv';...
    'RRD406 12072023 ABET.csv';...
    'RRD407 12132023 ABET.csv';...
    'RRD408 12152023 ABET.csv';...
    'RRD409 12152023 ABET.csv';...
    'RRD410 12162023 ABET.csv';...
    'RRD411 12132023 ABET.csv';...
    'RRD412 01052024 ABET.csv';...
    'RRD413 12162023 ABET.csv';...
    'RRD399 12182023 ABET.csv';...
    'RRD400 01032024 ABET.csv';...
    'RRD401 12132023 ABET.csv';...
    'RRD403 12132023 ABET.csv';...
    'RRD404 12132023 ABET.csv';...
    'RRD405 01092024 ABET.csv';...
    'RRD406 12132023 ABET.csv';...
    'RRD407 12182023 ABET.csv';...
    'RRD408 01052024 ABET.csv';...
    'RRD409 01032024 ABET.csv';...
    'RRD410 01032024 ABET.csv';...
    'RRD411 12182023 ABET.csv';...
    
};


BORIS_files = {...
    'RRD 399 RDT D1 BORIS.csv';...
    'RRD 400 RDT D1 BORIS.csv';...
    'RRD 401 RDT D1 BORIS.csv';...
    'RRD 403 RDT D1 BORIS.csv';...
    'RRD 404 RDT D1 BORIS.csv';...
    'RRD 405 RDT D1 BORIS.csv';...
    'RRD 406 RDT D1 BORIS.csv';...
    'RRD 407 RDT D1 BORIS.csv';...
    'RRD 408 RDT D1 BORIS.csv';...
    'RRD 409 RDT D1 BORIS.csv';...
    'RRD 410 RDT D1 BORIS.csv';...
    'RRD 411 RDT D1 BORIS.csv';...
    'RRD 412 RDT D1 BORIS.csv';...
    'RRD 413 RDT D1 BORIS.csv';...
};





RDT_Day = {...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
    'RDT D1';...
};








SLEAP_time_range_adjustment = [];
 

%%

for ii = 1:size(ABET_files)
    boris_file = BORIS_files{ii};
    ABET_file = ABET_files{ii};
    file_string = strsplit(ABET_file, ' ');
    animal_string = file_string(1);
    date_string = file_string(2);
    [BehavData,ABETfile,Descriptives, block_end, largeRewSide, smallRewSide, forced_trial_start, free_trial_start]=ABET2TableFn_Chamber_A_v6(ABET_file,[]);
    [BehavData, boris_Extract_tbl] = boris_to_table(boris_file, BehavData, block_end, largeRewSide, smallRewSide, SLEAP_time_range_adjustment, forced_trial_start, free_trial_start);
    Descriptives.large_aborts = sum(BehavData.type_binary == 1);
    Descriptives.small_aborts = sum(BehavData.type_binary == 2);
    Descriptives.large_aborts_b1 = sum(BehavData.type_binary == 1 & BehavData.Block == 1);
    Descriptives.large_aborts_b2 = sum(BehavData.type_binary == 1 & BehavData.Block == 2);
    Descriptives.large_aborts_b3 = sum(BehavData.type_binary == 1 & BehavData.Block == 3);

    Descriptives.small_aborts_b1 = sum(BehavData.type_binary == 2 & BehavData.Block == 1);
    Descriptives.small_aborts_b2 = sum(BehavData.type_binary == 2 & BehavData.Block == 2);
    Descriptives.small_aborts_b3 = sum(BehavData.type_binary == 2 & BehavData.Block == 3);
    Descriptives.large_aborts = sum(BehavData.type_binary == 1);
    Descriptives.small_aborts = sum(BehavData.type_binary == 2);
    Descriptives.large_aborts_b1 = sum(BehavData.type_binary == 1 & BehavData.Block == 1);
    Descriptives.large_aborts_b2 = sum(BehavData.type_binary == 1 & BehavData.Block == 2);
    Descriptives.large_aborts_b3 = sum(BehavData.type_binary == 1 & BehavData.Block == 3);

    Descriptives.small_aborts_b1 = sum(BehavData.type_binary == 2 & BehavData.Block == 1);
    Descriptives.small_aborts_b2 = sum(BehavData.type_binary == 2 & BehavData.Block == 2);
    Descriptives.small_aborts_b3 = sum(BehavData.type_binary == 2 & BehavData.Block == 3);



    indices = BehavData.ForceFree == 0 & (BehavData.bigSmall == 1.2 | BehavData.bigSmall == 0.3);
    BehavData_filtered = BehavData(indices, :);

    sequence = zeros(size(BehavData_filtered, 1), 1);
    % Initialize arrays to store the first time values
    forced_trial_start = zeros(3, 1); % For strings of 1s
    free_trial_start = zeros(3, 1); % For strings of 0s

    % Loop through the data
    for i = 1:size(BehavData_filtered, 1)
        if i == 1
            sequence(1) = 0;
            % Check if the current value in column 2 is different from the previous one
        elseif i > 1 && BehavData_filtered.bigSmall(i) ~= BehavData_filtered.bigSmall(i-1)

            % Store the first time for string of 1s
            sequence(i) = 0;
        else
            if BehavData_filtered.bigSmall(i) == 1.2
                % Store the first time for string of 0s
                sequence(i) = 1;
            elseif BehavData_filtered.bigSmall(i) == 0.3
                sequence(i) = 2;
            end
        end
    end

    % remove first trials, because they follow forced choice trials & thus
    % can't be a sequence
    rows_to_remove = [1 23 45];
    num_rows = height(BehavData_filtered);
    rows_to_remove = rows_to_remove(rows_to_remove <= num_rows);

    BehavData_filtered(rows_to_remove, :) = [];
    sequence(rows_to_remove, :) = [];
    sequences_poss = 21; % because there are 22 free choice trials, and there can't be a sequence on the 1st one of each block (because there are forced choice trials prior)
    BehavData_filtered.sequence = sequence;
    Descriptives.large_sequence_B1 = (sum(BehavData_filtered.Block == 1 & BehavData_filtered.sequence == 1)/sequences_poss)*100;
    Descriptives.large_sequence_B2 = (sum(BehavData_filtered.Block == 2 & BehavData_filtered.sequence == 1)/sequences_poss)*100;
    Descriptives.large_sequence_B3 = (sum(BehavData_filtered.Block == 3 & BehavData_filtered.sequence == 1)/sequences_poss)*100;

    Descriptives.small_sequence_B1 = (sum(BehavData_filtered.Block == 1 & BehavData_filtered.sequence == 2)/sequences_poss)*100;
    Descriptives.small_sequence_B2 = (sum(BehavData_filtered.Block == 2 & BehavData_filtered.sequence == 2)/sequences_poss)*100;
    Descriptives.small_sequence_B3 = (sum(BehavData_filtered.Block == 3 & BehavData_filtered.sequence == 2)/sequences_poss)*100;

    descriptives_table(ii, :) = [cell2table(animal_string) cell2table(date_string) Descriptives];
end

%%
writetable(descriptives_table,'descriptives_table.csv')